[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_ENV_VALIDATION = "1"
  NPM_FLAGS = "--production=false"

# Force Next.js to use Node.js runtime for API routes
[[edge_functions]]
  function = "nextjs"
  path = "/api/*"

# Redirect all other routes to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"